title: "-"
author: 帝归
email: unionx@foxmail.com
description: 生命，计算，以及其他
url: "http://unionx.me"
permalink: /:year/:month/:day/:title.html
twitter_username: unionx
github_username:  unionx

gems: [jekyll-paginate]
paginate: 10
